@tool
class_name AppReleaseRunContext
extends RefCounted

## Materialises the configuration for one run into `<project>/.release_tools/`.
##
## `release_config.tres` cannot be read from bash or Ruby, so the resolved settings
## are written out twice just before a child process starts:
##
## - `run.env` — `KEY="value"` lines, `source`-able by `release.sh` and loaded by
##   fastlane through dotenv.
## - `config.json` — the same identity data for `list_releases.rb`, which parses
##   JSON natively and therefore needs no `jq`.
##
## Both files are per-project scratch data and belong in `.gitignore`.

static func work_dir() -> String:
	var path := ProjectSettings.globalize_path(AppReleaseStrings.resource_path_prefix).path_join(
		AppReleaseStrings.work_dir_name
	)
	DirAccess.make_dir_recursive_absolute(path)
	return path


static func run_env_path() -> String:
	return work_dir().path_join(AppReleaseStrings.run_env_file_name)


static func run_config_path() -> String:
	return work_dir().path_join(AppReleaseStrings.run_config_file_name)


static func releases_path(store_id: String) -> String:
	return work_dir().path_join(AppReleaseStrings.releases_file_format % store_id)


static func write_run_env(
	config: AppReleaseConfig,
	target: AppReleaseTarget,
	version: String,
	build: int,
	notes_file: String,
	groups: String,
	debug_build: bool,
) -> Error:
	var root := ProjectSettings.globalize_path(AppReleaseStrings.resource_path_prefix)
	var values: Dictionary = {
		AppReleaseStrings.env_target_id: target.target_id(),
		AppReleaseStrings.env_target_label: target.display_label(),
		AppReleaseStrings.env_platform: target.platform,
		AppReleaseStrings.env_store: target.store_id(),
		AppReleaseStrings.env_lane: target.fastlane_lane,
		AppReleaseStrings.env_export_preset: target.export_preset,
		AppReleaseStrings.env_build_mode: AppReleaseTarget.BuildMode.keys()[target.build_mode],
		AppReleaseStrings.env_artifact_path: target.resolved_artifact_path(),
		AppReleaseStrings.env_play_track: target.play_track,
		AppReleaseStrings.env_app_identifier: config.bundle_identifier_for(target.platform),
		AppReleaseStrings.env_android_package_name: config.android_package_name,
		AppReleaseStrings.env_apple_team_id: config.apple_team_id,
		AppReleaseStrings.env_native_project_path: target.native_project_path,
		AppReleaseStrings.env_xcode_scheme: target.xcode_scheme,
		AppReleaseStrings.env_ios_export_options: target.export_options_plist,
		AppReleaseStrings.env_pck_path: target.pck_path,
		AppReleaseStrings.env_project_root: root.rstrip("/"),
		AppReleaseStrings.env_godot_bin: AppReleaseProcess.godot_binary(
			config.godot_binary_path_override
		),
		AppReleaseStrings.env_logs_dir: config.logs_dir,
		AppReleaseStrings.env_release_notes_dir: config.release_notes_dir,
		AppReleaseStrings.env_play_changelogs_dir: config.play_changelogs_dir,
		AppReleaseStrings.env_keep_logs: str(config.keep_logs),
		AppReleaseStrings.env_extra_path: AppReleaseProcess.build_ruby_paths_sorted_by_usability(config.extra_path_entries),
		AppReleaseStrings.env_debug_build: "1" if debug_build else "0",
		AppReleaseStrings.env_version: version,
		AppReleaseStrings.env_build: str(build),
		AppReleaseStrings.env_release_notes_file: notes_file,
		AppReleaseStrings.env_release_groups: groups if target.supports_tester_groups else "",
	}

	var lines: PackedStringArray = [
		"# Generated by the App Release plugin. Overwritten on every run — do not edit.",
	]
	for key in values:
		lines.append("%s=\"%s\"" % [key, _escape(str(values[key]))])
	lines.append("")

	return _write(run_env_path(), "\n".join(lines))


static func write_run_config(config: AppReleaseConfig) -> Error:
	var stores: Dictionary = {}
	for target in config.enabled_targets():
		var store_id := target.store_id()
		if stores.has(store_id):
			continue
		stores[store_id] = {
			"platform": target.platform,
			"bundle_identifier": config.bundle_identifier_for(target.platform),
			"export_preset": target.export_preset,
		}

	var payload: Dictionary = {
		"project_root": ProjectSettings.globalize_path(
			AppReleaseStrings.resource_path_prefix
		).rstrip("/"),
		"stores": stores,
	}
	return _write(run_config_path(), JSON.stringify(payload, "\t"))

static func write_notes_file(notes: String, timestamp: String) -> String:
	if notes.strip_edges().is_empty():
		return ""
	var path := work_dir().path_join(AppReleaseStrings.notes_temp_file_format % timestamp)
	if _write(path, notes) != OK:
		return ""
	return path


static func _write(path: String, text: String) -> Error:
	var file := FileAccess.open(path, FileAccess.WRITE)
	if file == null:
		var error := FileAccess.get_open_error()
		push_error("App Release: cannot write %s (%s)." % [path, error_string(error)])
		return error
	file.store_string(text)
	file.close()
	return OK


static func _escape(value: String) -> String:
	return (
		value
		.replace("\\", "\\\\")
		.replace("\"", "\\\"")
		.replace("$", "\\$")
		.replace("`", "\\`")
	)
